theme: jekyll-theme-cayman
github:
  is_project_page: false
# remote_theme: pages-themes/slate@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Semaphore]
description: [Decentralized Social Media with a Chance of Working]
# show_downloads: [false]
